/**
 * Represents a Caesar shift cipher that generates an encoding by cyclically
 * shifting the set of valid characters defined in {@link Cipher#VALID_CHARS}.
 *
 * <p>
 * Each character is mapped to the character {@code shift} positions to the left
 * within {@code VALID_CHARS}, wrapping around to the front on overflow. This is
 * a specialization of {@link Substitution}.
 */
public class CaesarShift extends Substitution {

    /**
     * Constructs a Caesar shift with the specified shift amount.
     *
     * <p>
     * The encoding is generated by rotating {@link Cipher#VALID_CHARS} to the left
     * by {@code shift} positions.
     *
     * @param shift
     *            the number of positions to shift the valid character set; must be
     *            non-negative.
     * @throws IllegalArgumentException
     *             if {@code shift} is negative.
     */
    public CaesarShift(int shift) {
        super(buildEncoding(shift));
    }

    /**
     * Builds the encoding string for a Caesar shift cipher by rotating
     * {@link Cipher#VALID_CHARS} to the left by {@code shift} positions, with
     * wrapping on overflow.
     *
     * @param shift
     *            the number of positions to shift; must be non-negative.
     * @return the encoding string corresponding to the given shift.
     * @throws IllegalArgumentException
     *             if {@code shift} is negative.
     */
    private static String buildEncoding(int shift) {
        if (shift < 0) {
            throw new IllegalArgumentException();
        }

        String valid = Cipher.VALID_CHARS;

        shift = shift % valid.length();
        String encoding = valid.substring(shift) + valid.substring(0, shift);

        return encoding;
    }
}
